### ISSUE TITLE
CozoDB unexpected hang

### ISSUE THREAD

**Issue by DerZc** [cozodb/cozo#123]
Consider the following program:
```
eupk[a, b] <- [[null, "rO"], [null, "dc"], [null, "kcV74"], [null, "g9c"], [null, "4eQSOc6"]]
gmnx[a] <- [["CPaM4zVj"], ["2IGqsvTR"], ["ry3MRcc"], ["yFqMwcT48"], ["tL2jZZtNax"]]
egbh[a, b, c] <- [["ucGQdD", true, null], ["cBVuPWJM", true, null], ["We", false, null]]


iomf[E, C, C] := egbh[B, C, E]
otge[B, F, H, E, C] := iomf[B, H, _], gmnx[E], eupk[C, F]
ptuc[D, B, C] := iomf[C, D, D], eupk[B, _]
pyrc[A, F, H, G, I] := ptuc[A, E, F], gmnx[I], egbh[H, A, D], gmnx[G]
znoj[D, A] := (otge[D, _, A, _, D], otge[D, _, A, _, D], eupk[D, _], pyrc[A, D, _, _, _], pyrc[A, D, _, _, _], iomf[D, A, _])

?[a, b] := znoj[a, b]
```
There are five rules and not any recursion, but I got `Killed` when I run it with Python. I can also reproduce this hang in https://www.cozodb.org/wasm-demo/

This is the Python program:
```
from pycozo.client import Client

program = '''
eupk[a, b] <- [[null, "rO"], [null, "dc"], [null, "kcV74"], [null, "g9c"], [null, "4eQSOc6"]]
gmnx[a] <- [["CPaM4zVj"], ["2IGqsvTR"], ["ry3MRcc"], ["yFqMwcT48"], ["tL2jZZtNax"]]
egbh[a, b, c] <- [["ucGQdD", true, null], ["cBVuPWJM", true, null], ["We", false, null]]

iomf[E, C, C] := egbh[B, C, E]
otge[B, F, H, E, C] := iomf[B, H, _], gmnx[E], eupk[C, F]
ptuc[D, B, C] := iomf[C, D, D], eupk[B, _]
pyrc[A, F, H, G, I] := ptuc[A, E, F], gmnx[I], egbh[H, A, D], gmnx[G]

znoj[D, A] := (otge[D, _, A, _, D], otge[D, _, A, _, D], eupk[D, _], pyrc[A, D, _, _, _], pyrc[A, D, _, _, _], iomf[D, A, _])

?[a, b] := znoj[a, b]
'''
client = Client()
r = client.run(program)

print(r)
```
I run this program in Ubuntu 22.04 with Python 3.8.10

**Comment by zh217** [comment]
It's not really hanging, my machine completes it with `:disable_magic_rewrite true` in 8 seconds. Without this option it becomes much worse, but it is progressing nonetheless. The reason is that the program attempts to join multiple identical relations in `znoj` which leads to a combinatorial explosion of intermediate rows.

If you change
```
znoj[D, A] := (otge[D, _, A, _, D], otge[D, _, A, _, D], eupk[D, _], pyrc[A, D, _, _, _], pyrc[A, D, _, _, _], iomf[D, A, _])
```
to
```
znoj[D, A] := (otge[D, _, A, _, D], eupk[D, _], pyrc[A, D, _, _, _], pyrc[A, D, _, _, _], iomf[D, A, _])
```
it will be faster, further rewrite to
```
znoj[D, A] := (otge[D, _, A, _, D], eupk[D, _], pyrc[A, D, _, _, _], iomf[D, A, _])
```
Will make it instant.

The way CozoDB evaluates rows in a single stratum is by streaming values without any form of caching. Usually this is beneficial for performance, but this is clearly a case where this behaviour gets itself into trouble. But without pumping much more work into the optimizer, it is not clear what could be done to improve it (we can certainly eliminate repeated identical sub-expressions, but as this pattern doesn't occur in the wild, patching it up in this way doesn't bring much real benefits).

**Comment by DerZc** [comment]
I got it! Thank you very much for always patiently explaining! I close this issue.
