### ISSUE TITLE
Bug in OR function 

### ISSUE THREAD

**Issue by Volland** [cozodb/cozo#211]
I working on complex filtering that use or and end function . I got a wired behavior that could not explain 

Imagine we have a simple table 
:create stamps {stamp: String?}

and we want to run a query 

?[stamp] := *stamps[stamp],or (and (!is_null(stamp), stamp > '2021-12-31T00:00:00.000000Z'), and (!is_null(stamp) , stamp < '2022-12-31T00:00:00.000000Z' ))

I got error   help: comparison can only be done between the same datatypes, got null and "2021-12-31T00:00:00.000000Z"

if I run 
?[stamp] := *stamps[stamp],and (!is_null(stamp), stamp > '2021-12-31T00:00:00.000000Z')
all works as expected

**Comment by zh217** [comment]
This is actually the expected behaviour, since in CozoDB the order of
evaluation of `and`/`or` is unspecified. In particular, you cannot rely on
it to evaluate the arguments from left to right and short-circuit.

What you can do in this case is to use `coalesce` (or `~`) to coalesce null
values for a suitable value for comparison (the empty string should work in
this case).
