### ISSUE TITLE
Terminal REPL

### ISSUE THREAD

**Issue by rhn** [cozodb/cozo#31]
I just discovered CoZo, and with disappointment, I noticed that the simplest way to use it is through a browser, which is not that simple at all (not to mention security implications of leaving open network sockets even on localhost).

So I made a terminal-based REPL: https://paste.debian.net/1266001/

It's basic, but it works. Type a space to enter multi-line editing.

Are you interested in having that? Should I submit it as a binary in cozo? Or a separate crate?

**Comment by zh217** [comment]
Hi, thanks for your interest. I think the best way do go forward is to have an option in cozoserver to start a text-based REPL without opening the web server. If you don't mind, I can manually incorporate your code into the server code [here](https://github.com/cozodb/cozo/blob/main/cozoserver/src/main.rs) (which is also quite simple). Or you can submit a pull request for that. It's your call. We don't want more binaries since we already have way too many arfefacts to manage at the moment.

**Comment by rhn** [comment]
Go ahead, consider this a contribution. I offered a merge request in case you wanted to track further changes.

**Comment by zh217** [comment]
I've incorporated your code and the REPL functionality will be available for the next release. In the meantime, you can build it from the dev branch by

```
CARGO_PROFILE_RELEASE_LTO=fat cargo build --release -p cozoserver -F compact -F storage-rocksdb
```

I have made a few changes to how you print the values and error messages.
