### ISSUE TITLE
Custom functions defined in Rust (/ other host language)

### ISSUE THREAD

**Issue by GoldsteinE** [cozodb/cozo#36]
Hi! I’d like to embed Cozo in my project and provide some utility functions to queries. Currently I use fixed rules for this:

```prolog
urls[url] <- [["https://goldstein.rs"], ["https://cozodb.org"]]
fetched[url, status, body] <~ FetchUrl(urls[url])
query[url, body, selector] := fetched[url, status, body], selector = "title"
titles[] <~ HtmlSelect(query[url, body, selector])
?[url, title] := titles[url, titles], title = first(titles)
```

That works, but it’s kinda inconvenient. I’d prefer to define custom functions instead for API like this:

```prolog
urls[url] <- [["https://goldstein.rs"], ["https://cozodb.org"]]
?[url, title] := urls[url], body = fetch_url(url), title = first(html_select(body, "title"))
```

Is feature like this planned? Maybe I’m missing something, but it seems to be useful for embedding Cozo.

**Comment by zh217** [comment]
There is no plan to add custom functions. The reason is performance and parallelism. When you use fixed rules, the execution engine basically give you everything you need to compute the relation, and wait for you to finish all of it. You can do it in batch or one by one, it's up to you. Functions are different since they are called at least once for every row, sometimes more than once due to some optimizations (which is a problem if your function has side effects or is expensive to compute). There is also no guarantee at all about the order the functions are called for the rows. All of these make custom functions a very dangerous thing, since users who are not familiar with the intracacies can easily end up in a difficult situation, so we decided against implementing it. So unfortunately you have to use the long-winded way of writing the queries until we figure out something better.
