### ISSUE TITLE
Define concrete error types instead of `miette::Report`/`miette::Result`

### ISSUE THREAD

**Issue by ndrpnt** [cozodb/cozo#44]
Only application code should use catch-all error type [`miette::Report`](https://docs.rs/miette/latest/miette/struct.Report.html). Libraries should return their own concrete types that implement [`miette::Diagnostic`](https://docs.rs/miette/latest/miette/trait.Diagnostic.html). See [here](https://docs.rs/miette/latest/miette/#-in-application-code:~:text=Use%20this%20%60Result%60%20type%20(or%20its%20expanded%20version)%20as%20the%20return%20type%0Athroughout%20your%20app%20(but%20NOT%20your%20libraries!%20Those%20should%20always%20return%0Aconcrete%20types!).).

This is better design because it lets the user inspect the errors and doesn't force them to use `miette` in their application code.

**Comment by zh217** [comment]
Fair point. Cozo was originally intended to be an application that happens to be usable as a library, though it seems that lots of people use it as a library proper now. I will see what we can do about it.

Note that naive replacement of errors by enum-style errors will actually have a negative impact on performance (we measured before) since I believe miette used some clever tricks under the hook.

**Comment by zh217** [comment]
I agree, will reopen it for the moment. Don't have a timeline for the fix though.

**Comment by zh217** [comment]
After looking at this problem in details, we have decided just to leave the handling of errors in CozoDB in the present state. The rationales:

* The suggestions that library code should return concrete error types apply mostly to small libraries where an Enum-style error suffices. In Cozo this Enum would contain hundreds or more different types. This won't be helpful to the user at all.
* The user code is also often not in a position to "fix" any of these errors, all they can do is to report it. In the rare circumstances where the user code can fix the problem for specific types of error, `err.code()` and `err.labels()` should suffice to give enough information.
* Also there is the problem of error size. A simple-minded implementation of errors would result in large Result type size. Again, this only arises because in a database at any instance there is simply too many ways to go wrong. We can do lots of boxing and maybe even some unsafe to improve performance, but then the user is left with some error types that are hard to understand and manipulate.
* Such optimizations have already been done by crates like miette, and people are familiar with it. So using miette errors throughout actually helps the user instead of the other way around.
* In a way, you can say that CozoDB is more like an application than a library. It is composed of many constituents, many of them also have immense internal complexities. It just happens that you can use it as a library in user code as well.
