### ISSUE TITLE
Set up, or allow someone else to set up, suitable communication spaces

### ISSUE THREAD

**Issue by gisborne** [cozodb/cozo#70]
After this hit HN, I imagine there are quite a few interested folks. But even if the number of such folks is 10, it would be great to have somewhere to share information about this VERY exciting project.

I would be happy to set up and moderate a r/cozodb Reddit group.

I could just do this, of course, but it would be much more effective if the documentation and readme called out this space, and we had participation from the developer (even if only occasionally).

**Comment by zh217** [comment]
It's good to know you're planning on setting up a r/cozodb Reddit group! Having a space for people to share information about this project is definitely a positive step. Regarding my participation, I must consider my workload before committing to anything. While I'd like to contribute when possible, my availability might fluctuate depending on my schedule.

Thanks for taking the initiative to create this platform, and I will definitely put it into the README and other places when it's up.

**Comment by Joshfindit** [comment]
A s a potential user, I have ~2TB of 'personal archaeology' data (not including video): Photos, audio recordings (not with transcripts courtesy of whisper), message archives, google location records, personal notes, code, archived projects, and so-on.

I'm not sure if that's a compelling enough dataset to interest you @zh217, but if so; I (or we the community) could do the bulk of the work with intermittent and non-committal input from you. Personally I'm mainly a Ruby + JavaScript/Typescript + graphDB dev but CozoDB might be the tool that finally unlocks all metadata in my archive and for that I'm willing to learn a new stack.

**Comment by zh217** [comment]
@Joshfindit, I understand that your values are quite large. In that case, you'll definitely want to check out [this note](https://docs.cozodb.org/en/latest/stored.html#storing-large-values). My use cases don't involve datasets of this size, but I'm very interested in how well CozoDB handles them. With the RocksDB backend, it will probably work just fine. If any issues arise, we can explore what needs to be done to support it (RocksDB can definitely handle datasets this large, but it might need some tweaking for efficiency).

I'm on board with the idea of offering intermittent and non-committal input as my schedule permits. It's always great to see how others make use of tools and technologies, and I look forward to following your progress. As for myself, I currently need more and more text processing within CozoDB (mainly due to the current wave of AI). So, I'm working on two features: full-text search and text deduplication within CozoDB, similar to vector search. These will be released in the coming weeks.

**Comment by gisborne** [comment]
I've created r/cozodb

**Comment by zh217** [comment]
It's done.
