### ISSUE TITLE
How to query w/a validity field in a vector query?

### ISSUE THREAD

**Issue by SamMakesThings** [cozodb/cozo#92]
So the way to query for the most recent version of a relation w/Validity (time travel) is

`?[uid, mood] := *status{uid, mood @ 'NOW'}`

But how can I do the same with a vector query? I tried

`?[uid, mood] := ~status:index{uid, mood @ 'NOW' | query: q, k: 5, ef: 20}, q = vec(<vectors here>)`

And that failed with the error "The query parser has encountered unexpected input / end of input at 47..47". No idea how to structure this query, hard to find more information on how the vector query is structured

**Comment by zh217** [comment]
This is not possible now. HNSW and time travel both rely on rather intricate algorithms, and I am not aware of any good ways to combine these two.

Suggestions are welcome on how to do it.

**Comment by SamMakesThings** [comment]
Hmm - good to know. I can take a look, but unfortunately this isn't my area of expertise - am unlikely to be useful there

**Comment by SamMakesThings** [comment]
A possible hacky (temporary) way to do this, if most things aren't updated frequently:

- Do a vector query with ~5x the actual target items
- Query the resulting relation w/the time travel @ 'NOW' assertion
- If resulting amount is less than the target items, repeated the process

My target queries are likely to be small for a while - do you think this would work ok?

**Comment by SamMakesThings** [comment]
There's other query logic I wanted to do as well, e.g. use another column (salience) in addition to the vector query to output the final result. Would the above work for that?

**Comment by zh217** [comment]
No, it doesn't work, as only stored relations support time travelling. (And it doesn't work either even if non-stored time travelling were supported: think what happens if the nearest neighbour recently "moved" to far away.)

One way to do it is to get all the potential vectors first by using the timed query, and then calculate (by using the distance function directly) the distance, then sort. But if the first step generates many candidates, this will be very slow.
